alter table public.jobs
  add column if not exists role text,
  add column if not exists modality text,
  add column if not exists state text,
  add column if not exists city text,
  add column if not exists salary text,
  add column if not exists salary_min text,
  add column if not exists salary_max text,
  add column if not exists remuneration_type text,
  add column if not exists has_bonus boolean not null default false,
  add column if not exists bonus_type text,
  add column if not exists bonus_value text,
  add column if not exists contract_type text,
  add column if not exists description text,
  add column if not exists requirements text[] not null default array[]::text[],
  add column if not exists stages text[] not null default array[]::text[],
  add column if not exists work_schedule text,
  add column if not exists min_age integer,
  add column if not exists is_first_job boolean not null default false,
  add column if not exists is_pcd boolean not null default false,
  add column if not exists pcd_details text,
  add column if not exists positions integer not null default 1,
  add column if not exists request_reason text,
  add column if not exists is_urgent boolean not null default false,
  add column if not exists responsibilities text,
  add column if not exists benefits jsonb not null default '{}'::jsonb,
  add column if not exists status text not null default 'active',
  add column if not exists created_at timestamptz not null default now();

notify pgrst, 'reload schema';
